<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkillSeeder extends Seeder
{
    public function run(): void
    {
        $skills = [
            // 🧠 Cognitive & Thinking Skills
            ['Skill_Title' => 'Critical thinking', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Thinking'],
            ['Skill_Title' => 'Logical reasoning', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Thinking'],
            ['Skill_Title' => 'Problem solving', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Thinking'],
            ['Skill_Title' => 'Decision making', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Thinking'],
            ['Skill_Title' => 'Analytical thinking', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Thinking'],
            ['Skill_Title' => 'Creative thinking', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Thinking'],
            ['Skill_Title' => 'Strategic thinking', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Thinking'],
            ['Skill_Title' => 'Systems thinking', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Thinking'],
            ['Skill_Title' => 'Abstract thinking', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Thinking'],
            ['Skill_Title' => 'Spatial reasoning', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Thinking'],
            ['Skill_Title' => 'Pattern recognition', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Thinking'],
            ['Skill_Title' => 'Memory', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Thinking'],
            ['Skill_Title' => 'Concentration', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Thinking'],
            ['Skill_Title' => 'Observation', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Thinking'],
            ['Skill_Title' => 'Research', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Research'],
            ['Skill_Title' => 'Information analysis', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Research'],
            ['Skill_Title' => 'Mathematical reasoning', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Math'],
            ['Skill_Title' => 'Risk analysis', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Thinking'],
            ['Skill_Title' => 'Planning', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Thinking'],
            ['Skill_Title' => 'Prioritization', 'Category' => 'Cognitive & Thinking', 'Subcategory' => 'Thinking'],

            // 🗣️ Communication Skills
            ['Skill_Title' => 'Speaking', 'Category' => 'Communication', 'Subcategory' => 'Verbal'],
            ['Skill_Title' => 'Writing', 'Category' => 'Communication', 'Subcategory' => 'Written'],
            ['Skill_Title' => 'Reading', 'Category' => 'Communication', 'Subcategory' => 'Reading'],
            ['Skill_Title' => 'Listening', 'Category' => 'Communication', 'Subcategory' => 'Verbal'],
            ['Skill_Title' => 'Public speaking', 'Category' => 'Communication', 'Subcategory' => 'Verbal'],
            ['Skill_Title' => 'Presentation', 'Category' => 'Communication', 'Subcategory' => 'Verbal'],
            ['Skill_Title' => 'Storytelling', 'Category' => 'Communication', 'Subcategory' => 'Verbal'],
            ['Skill_Title' => 'Debate', 'Category' => 'Communication', 'Subcategory' => 'Verbal'],
            ['Skill_Title' => 'Negotiation', 'Category' => 'Communication', 'Subcategory' => 'Interpersonal'],
            ['Skill_Title' => 'Persuasion', 'Category' => 'Communication', 'Subcategory' => 'Interpersonal'],
            ['Skill_Title' => 'Interviewing', 'Category' => 'Communication', 'Subcategory' => 'Verbal'],
            ['Skill_Title' => 'Teaching', 'Category' => 'Communication', 'Subcategory' => 'Instruction'],
            ['Skill_Title' => 'Explaining', 'Category' => 'Communication', 'Subcategory' => 'Instruction'],
            ['Skill_Title' => 'Technical writing', 'Category' => 'Communication', 'Subcategory' => 'Written'],
            ['Skill_Title' => 'Copywriting', 'Category' => 'Communication', 'Subcategory' => 'Written'],
            ['Skill_Title' => 'Translation', 'Category' => 'Communication', 'Subcategory' => 'Written'],
            ['Skill_Title' => 'Nonverbal communication', 'Category' => 'Communication', 'Subcategory' => 'Verbal'],
            ['Skill_Title' => 'Active listening', 'Category' => 'Communication', 'Subcategory' => 'Listening'],

            // 🤝 Social & Interpersonal Skills
            ['Skill_Title' => 'Teamwork', 'Category' => 'Social & Interpersonal', 'Subcategory' => 'Collaboration'],
            ['Skill_Title' => 'Cooperation', 'Category' => 'Social & Interpersonal', 'Subcategory' => 'Collaboration'],
            ['Skill_Title' => 'Leadership', 'Category' => 'Social & Interpersonal', 'Subcategory' => 'Leadership'],
            ['Skill_Title' => 'Conflict resolution', 'Category' => 'Social & Interpersonal', 'Subcategory' => 'Leadership'],
            ['Skill_Title' => 'Business networking', 'Category' => 'Social & Interpersonal', 'Subcategory' => 'Relationship'],
            ['Skill_Title' => 'Empathy', 'Category' => 'Social & Interpersonal', 'Subcategory' => 'Relationship'],
            ['Skill_Title' => 'Relationship building', 'Category' => 'Social & Interpersonal', 'Subcategory' => 'Relationship'],
            ['Skill_Title' => 'Mentoring', 'Category' => 'Social & Interpersonal', 'Subcategory' => 'Leadership'],
            ['Skill_Title' => 'Coaching', 'Category' => 'Social & Interpersonal', 'Subcategory' => 'Leadership'],
            ['Skill_Title' => 'Collaboration', 'Category' => 'Social & Interpersonal', 'Subcategory' => 'Collaboration'],
            ['Skill_Title' => 'Diplomacy', 'Category' => 'Social & Interpersonal', 'Subcategory' => 'Relationship'],
            ['Skill_Title' => 'Emotional intelligence', 'Category' => 'Social & Interpersonal', 'Subcategory' => 'Self-Awareness'],
            ['Skill_Title' => 'Customer service', 'Category' => 'Social & Interpersonal', 'Subcategory' => 'Service'],
            ['Skill_Title' => 'Community building', 'Category' => 'Social & Interpersonal', 'Subcategory' => 'Leadership'],
            ['Skill_Title' => 'People management', 'Category' => 'Social & Interpersonal', 'Subcategory' => 'Leadership'],

            // 🎨 Creative & Artistic Skills
            ['Skill_Title' => 'Drawing', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Visual Arts'],
            ['Skill_Title' => 'Painting', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Visual Arts'],
            ['Skill_Title' => 'Illustration', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Visual Arts'],
            ['Skill_Title' => 'Sculpture', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Visual Arts'],
            ['Skill_Title' => 'Photography', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Visual Media'],
            ['Skill_Title' => 'Graphic design', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Design'],
            ['Skill_Title' => 'UI design', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Design'],
            ['Skill_Title' => 'UX design', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Design'],
            ['Skill_Title' => 'Animation', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Motion Graphics'],
            ['Skill_Title' => '3D modeling', 'Category' => 'Creative & Artistic', 'Subcategory' => '3D Design'],
            ['Skill_Title' => 'Video editing', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Video'],
            ['Skill_Title' => 'Filmmaking', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Video'],
            ['Skill_Title' => 'Music composition', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Music'],
            ['Skill_Title' => 'Singing', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Music'],
            ['Skill_Title' => 'Dancing', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Performance'],
            ['Skill_Title' => 'Acting', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Performance'],
            ['Skill_Title' => 'Creative writing', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Writing'],
            ['Skill_Title' => 'Poetry', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Writing'],
            ['Skill_Title' => 'Fashion design', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Design'],
            ['Skill_Title' => 'Interior design', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Design'],
            ['Skill_Title' => 'Calligraphy', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Visual Arts'],
            ['Skill_Title' => 'Handicraft', 'Category' => 'Creative & Artistic', 'Subcategory' => 'Handicraft'],

            // 💻 Technology & Computer Skills
            ['Skill_Title' => 'Computer operation', 'Category' => 'Technology', 'Subcategory' => 'Operations'],
            ['Skill_Title' => 'Programming', 'Category' => 'Technology', 'Subcategory' => 'Development'],
            ['Skill_Title' => 'Web development', 'Category' => 'Technology', 'Subcategory' => 'Development'],
            ['Skill_Title' => 'Mobile development', 'Category' => 'Technology', 'Subcategory' => 'Development'],
            ['Skill_Title' => 'Software development', 'Category' => 'Technology', 'Subcategory' => 'Development'],
            ['Skill_Title' => 'Database management', 'Category' => 'Technology', 'Subcategory' => 'Data'],
            ['Skill_Title' => 'SQL', 'Category' => 'Technology', 'Subcategory' => 'Data'],
            ['Skill_Title' => 'Networking', 'Category' => 'Technology', 'Subcategory' => 'Infrastructure'],
            ['Skill_Title' => 'Cloud computing', 'Category' => 'Technology', 'Subcategory' => 'Infrastructure'],
            ['Skill_Title' => 'System administration', 'Category' => 'Technology', 'Subcategory' => 'Administration'],
            ['Skill_Title' => 'DevOps', 'Category' => 'Technology', 'Subcategory' => 'Administration'],
            ['Skill_Title' => 'Data analysis', 'Category' => 'Technology', 'Subcategory' => 'Data'],
            ['Skill_Title' => 'Data science', 'Category' => 'Technology', 'Subcategory' => 'Data Science'],
            ['Skill_Title' => 'Artificial intelligence', 'Category' => 'Technology', 'Subcategory' => 'AI'],
            ['Skill_Title' => 'Machine learning', 'Category' => 'Technology', 'Subcategory' => 'AI'],
            ['Skill_Title' => 'Digital forensics', 'Category' => 'Technology', 'Subcategory' => 'Security'],
            ['Skill_Title' => 'IT support', 'Category' => 'Technology', 'Subcategory' => 'Support'],
            ['Skill_Title' => 'Hardware repair', 'Category' => 'Technology', 'Subcategory' => 'Support'],
            ['Skill_Title' => 'Electronics', 'Category' => 'Technology', 'Subcategory' => 'Hardware'],
            ['Skill_Title' => '3D printing', 'Category' => 'Technology', 'Subcategory' => 'Manufacturing'],
            ['Skill_Title' => 'CAD', 'Category' => 'Technology', 'Subcategory' => 'Design'],
            ['Skill_Title' => 'Automation', 'Category' => 'Technology', 'Subcategory' => 'Engineering'],
            ['Skill_Title' => 'Robotics', 'Category' => 'Technology', 'Subcategory' => 'Engineering'],

            // 🔬 Scientific & Technical Skills
            ['Skill_Title' => 'Scientific research', 'Category' => 'Scientific & Technical', 'Subcategory' => 'Research'],
            ['Skill_Title' => 'Experimentation', 'Category' => 'Scientific & Technical', 'Subcategory' => 'Research'],
            ['Skill_Title' => 'Laboratory techniques', 'Category' => 'Scientific & Technical', 'Subcategory' => 'Lab'],
            ['Skill_Title' => 'Data collection', 'Category' => 'Scientific & Technical', 'Subcategory' => 'Research'],
            ['Skill_Title' => 'Statistical analysis', 'Category' => 'Scientific & Technical', 'Subcategory' => 'Data Science'],
            ['Skill_Title' => 'Scientific writing', 'Category' => 'Scientific & Technical', 'Subcategory' => 'Writing'],
            ['Skill_Title' => 'Engineering', 'Category' => 'Scientific & Technical', 'Subcategory' => 'Engineering'],
            ['Skill_Title' => 'Chemistry techniques', 'Category' => 'Scientific & Technical', 'Subcategory' => 'Lab'],
            ['Skill_Title' => 'Biology techniques', 'Category' => 'Scientific & Technical', 'Subcategory' => 'Lab'],
            ['Skill_Title' => 'Physics techniques', 'Category' => 'Scientific & Technical', 'Subcategory' => 'Lab'],
            ['Skill_Title' => 'Geological analysis', 'Category' => 'Scientific & Technical', 'Subcategory' => 'Research'],
            ['Skill_Title' => 'Environmental analysis', 'Category' => 'Scientific & Technical', 'Subcategory' => 'Research'],
            ['Skill_Title' => 'Measurement', 'Category' => 'Scientific & Technical', 'Subcategory' => 'Lab'],
            ['Skill_Title' => 'Technical drawing', 'Category' => 'Scientific & Technical', 'Subcategory' => 'Design'],
            ['Skill_Title' => 'Quality control', 'Category' => 'Scientific & Technical', 'Subcategory' => 'Engineering'],

            // 🔧 Practical / Hands-On Skills
            ['Skill_Title' => 'Carpentry', 'Category' => 'Practical', 'Subcategory' => 'Construction'],
            ['Skill_Title' => 'Plumbing', 'Category' => 'Practical', 'Subcategory' => 'Construction'],
            ['Skill_Title' => 'Welding', 'Category' => 'Practical', 'Subcategory' => 'Manufacturing'],
            ['Skill_Title' => 'Metalworking', 'Category' => 'Practical', 'Subcategory' => 'Manufacturing'],
            ['Skill_Title' => 'Masonry', 'Category' => 'Practical', 'Subcategory' => 'Construction'],
            ['Skill_Title' => 'Electrical work', 'Category' => 'Practical', 'Subcategory' => 'Electronics'],
            ['Skill_Title' => 'Painting walls', 'Category' => 'Practical', 'Subcategory' => 'Finishing'],
            ['Skill_Title' => 'Furniture making', 'Category' => 'Practical', 'Subcategory' => 'Woodwork'],
            ['Skill_Title' => 'Sewing', 'Category' => 'Practical', 'Subcategory' => 'Crafts'],
            ['Skill_Title' => 'Knitting', 'Category' => 'Practical', 'Subcategory' => 'Crafts'],
            ['Skill_Title' => 'Gardening', 'Category' => 'Practical', 'Subcategory' => 'Outdoor'],
            ['Skill_Title' => 'Landscaping', 'Category' => 'Practical', 'Subcategory' => 'Outdoor'],
            ['Skill_Title' => 'Appliance repair', 'Category' => 'Practical', 'Subcategory' => 'Repair'],
            ['Skill_Title' => 'Automotive repair', 'Category' => 'Practical', 'Subcategory' => 'Vehicle'],
            ['Skill_Title' => 'Motorcycle repair', 'Category' => 'Practical', 'Subcategory' => 'Vehicle'],
            ['Skill_Title' => 'Bicycle repair', 'Category' => 'Practical', 'Subcategory' => 'Vehicle'],
            ['Skill_Title' => 'Construction', 'Category' => 'Practical', 'Subcategory' => 'Construction'],
            ['Skill_Title' => 'Woodworking', 'Category' => 'Practical', 'Subcategory' => 'Woodwork'],
            ['Skill_Title' => 'Machining', 'Category' => 'Practical', 'Subcategory' => 'Manufacturing'],
            ['Skill_Title' => 'Tool use', 'Category' => 'Practical', 'Subcategory' => 'General'],

            // 🍳 Household & Domestic Skills
            ['Skill_Title' => 'Cooking', 'Category' => 'Household', 'Subcategory' => 'Food'],
            ['Skill_Title' => 'Baking', 'Category' => 'Household', 'Subcategory' => 'Food'],
            ['Skill_Title' => 'Meal preparation', 'Category' => 'Household', 'Subcategory' => 'Food'],
            ['Skill_Title' => 'Cleaning', 'Category' => 'Household', 'Subcategory' => 'Maintenance'],
            ['Skill_Title' => 'Laundry', 'Category' => 'Household', 'Subcategory' => 'Maintenance'],
            ['Skill_Title' => 'Ironing', 'Category' => 'Household', 'Subcategory' => 'Maintenance'],
            ['Skill_Title' => 'Home organization', 'Category' => 'Household', 'Subcategory' => 'Maintenance'],
            ['Skill_Title' => 'Basic home repair', 'Category' => 'Household', 'Subcategory' => 'Repair'],
            ['Skill_Title' => 'Food preservation', 'Category' => 'Household', 'Subcategory' => 'Food'],
            ['Skill_Title' => 'Childcare', 'Category' => 'Household', 'Subcategory' => 'Care'],
            ['Skill_Title' => 'Pet care', 'Category' => 'Household', 'Subcategory' => 'Care'],

            // 💼 Business & Professional Skills
            ['Skill_Title' => 'Project management', 'Category' => 'Business & Professional', 'Subcategory' => 'Management'],
            ['Skill_Title' => 'Business management', 'Category' => 'Business & Professional', 'Subcategory' => 'Management'],
            ['Skill_Title' => 'Entrepreneurship', 'Category' => 'Business & Professional', 'Subcategory' => 'Management'],
            ['Skill_Title' => 'Marketing', 'Category' => 'Business & Professional', 'Subcategory' => 'Marketing'],
            ['Skill_Title' => 'Sales', 'Category' => 'Business & Professional', 'Subcategory' => 'Marketing'],
            ['Skill_Title' => 'Accounting', 'Category' => 'Business & Professional', 'Subcategory' => 'Finance'],
            ['Skill_Title' => 'Bookkeeping', 'Category' => 'Business & Professional', 'Subcategory' => 'Finance'],
            ['Skill_Title' => 'Finance', 'Category' => 'Business & Professional', 'Subcategory' => 'Finance'],
            ['Skill_Title' => 'Human resources', 'Category' => 'Business & Professional', 'Subcategory' => 'Management'],
            ['Skill_Title' => 'Recruiting', 'Category' => 'Business & Professional', 'Subcategory' => 'HR'],
            ['Skill_Title' => 'Management', 'Category' => 'Business & Professional', 'Subcategory' => 'Leadership'],
            ['Skill_Title' => 'Customer relations', 'Category' => 'Business & Professional', 'Subcategory' => 'Service'],
            ['Skill_Title' => 'Business analysis', 'Category' => 'Business & Professional', 'Subcategory' => 'Analysis'],
            ['Skill_Title' => 'Product management', 'Category' => 'Business & Professional', 'Subcategory' => 'Management'],
            ['Skill_Title' => 'Operations management', 'Category' => 'Business & Professional', 'Subcategory' => 'Management'],
            ['Skill_Title' => 'Supply-chain management', 'Category' => 'Business & Professional', 'Subcategory' => 'Operations'],
            ['Skill_Title' => 'Procurement', 'Category' => 'Business & Professional', 'Subcategory' => 'Operations'],
            ['Skill_Title' => 'Administration', 'Category' => 'Business & Professional', 'Subcategory' => 'Management'],

            // 📚 Academic & Learning Skills
            ['Skill_Title' => 'Studying', 'Category' => 'Academic', 'Subcategory' => 'Learning'],
            ['Skill_Title' => 'Note-taking', 'Category' => 'Academic', 'Subcategory' => 'Learning'],
            ['Skill_Title' => 'Memorization', 'Category' => 'Academic', 'Subcategory' => 'Learning'],
            ['Skill_Title' => 'Essay writing', 'Category' => 'Academic', 'Subcategory' => 'Writing'],
            ['Skill_Title' => 'Report writing', 'Category' => 'Academic', 'Subcategory' => 'Writing'],
            ['Skill_Title' => 'Citation', 'Category' => 'Academic', 'Subcategory' => 'Writing'],
            ['Skill_Title' => 'Reading comprehension', 'Category' => 'Academic', 'Subcategory' => 'Reading'],
            ['Skill_Title' => 'Exam preparation', 'Category' => 'Academic', 'Subcategory' => 'Learning'],
            ['Skill_Title' => 'Information literacy', 'Category' => 'Academic', 'Subcategory' => 'Learning'],
            ['Skill_Title' => 'Media literacy', 'Category' => 'Academic', 'Subcategory' => 'Learning'],
            ['Skill_Title' => 'Academic presentation', 'Category' => 'Academic', 'Subcategory' => 'Presentation'],
            ['Skill_Title' => 'Language learning', 'Category' => 'Academic', 'Subcategory' => 'Languages'],
            ['Skill_Title' => 'Self-directed learning', 'Category' => 'Academic', 'Subcategory' => 'Learning'],

            // 🧘 Personal & Self-Management Skills
            ['Skill_Title' => 'Time management', 'Category' => 'Personal', 'Subcategory' => 'Organization'],
            ['Skill_Title' => 'Self-discipline', 'Category' => 'Personal', 'Subcategory' => 'Mindset'],
            ['Skill_Title' => 'Goal setting', 'Category' => 'Personal', 'Subcategory' => 'Mindset'],
            ['Skill_Title' => 'Organization', 'Category' => 'Personal', 'Subcategory' => 'Organization'],
            ['Skill_Title' => 'Stress management', 'Category' => 'Personal', 'Subcategory' => 'Health'],
            ['Skill_Title' => 'Adaptability', 'Category' => 'Personal', 'Subcategory' => 'Mindset'],
            ['Skill_Title' => 'Patience', 'Category' => 'Personal', 'Subcategory' => 'Mindset'],
            ['Skill_Title' => 'Motivation', 'Category' => 'Personal', 'Subcategory' => 'Mindset'],
            ['Skill_Title' => 'Self-awareness', 'Category' => 'Personal', 'Subcategory' => 'Mindset'],
            ['Skill_Title' => 'Self-control', 'Category' => 'Personal', 'Subcategory' => 'Mindset'],
            ['Skill_Title' => 'Resilience', 'Category' => 'Personal', 'Subcategory' => 'Mindset'],
            ['Skill_Title' => 'Habit building', 'Category' => 'Personal', 'Subcategory' => 'Mindset'],
            ['Skill_Title' => 'Personal finance', 'Category' => 'Personal', 'Subcategory' => 'Finance'],
            ['Skill_Title' => 'Personal organization', 'Category' => 'Personal', 'Subcategory' => 'Organization'],

            // 🏃 Physical & Athletic Skills
            ['Skill_Title' => 'Running', 'Category' => 'Physical', 'Subcategory' => 'Cardio'],
            ['Skill_Title' => 'Swimming', 'Category' => 'Physical', 'Subcategory' => 'Cardio'],
            ['Skill_Title' => 'Cycling', 'Category' => 'Physical', 'Subcategory' => 'Cardio'],
            ['Skill_Title' => 'Hiking', 'Category' => 'Physical', 'Subcategory' => 'Outdoor'],
            ['Skill_Title' => 'Climbing', 'Category' => 'Physical', 'Subcategory' => 'Strength'],
            ['Skill_Title' => 'Jumping', 'Category' => 'Physical', 'Subcategory' => 'Agility'],
            ['Skill_Title' => 'Balance', 'Category' => 'Physical', 'Subcategory' => 'Fitness'],
            ['Skill_Title' => 'Flexibility', 'Category' => 'Physical', 'Subcategory' => 'Fitness'],
            ['Skill_Title' => 'Strength training', 'Category' => 'Physical', 'Subcategory' => 'Strength'],
            ['Skill_Title' => 'Martial arts', 'Category' => 'Physical', 'Subcategory' => 'Combat'],
            ['Skill_Title' => 'Boxing', 'Category' => 'Physical', 'Subcategory' => 'Combat'],
            ['Skill_Title' => 'Wrestling', 'Category' => 'Physical', 'Subcategory' => 'Combat'],
            ['Skill_Title' => 'Basketball', 'Category' => 'Physical', 'Subcategory' => 'Sports'],
            ['Skill_Title' => 'Football', 'Category' => 'Physical', 'Subcategory' => 'Sports'],
            ['Skill_Title' => 'Soccer', 'Category' => 'Physical', 'Subcategory' => 'Sports'],
            ['Skill_Title' => 'Volleyball', 'Category' => 'Physical', 'Subcategory' => 'Sports'],
            ['Skill_Title' => 'Tennis', 'Category' => 'Physical', 'Subcategory' => 'Sports'],
            ['Skill_Title' => 'Badminton', 'Category' => 'Physical', 'Subcategory' => 'Sports'],
            ['Skill_Title' => 'Skateboarding', 'Category' => 'Physical', 'Subcategory' => 'Sports'],
            ['Skill_Title' => 'Gymnastics', 'Category' => 'Physical', 'Subcategory' => 'Sports'],

            // 🚗 Transportation & Navigation Skills
            ['Skill_Title' => 'Driving', 'Category' => 'Transportation', 'Subcategory' => 'Vehicle'],
            ['Skill_Title' => 'Motorcycle riding', 'Category' => 'Transportation', 'Subcategory' => 'Vehicle'],
            ['Skill_Title' => 'Bicycle riding', 'Category' => 'Transportation', 'Subcategory' => 'Vehicle'],
            ['Skill_Title' => 'Boat handling', 'Category' => 'Transportation', 'Subcategory' => 'Vehicle'],
            ['Skill_Title' => 'Navigation', 'Category' => 'Transportation', 'Subcategory' => 'Navigation'],
            ['Skill_Title' => 'Map reading', 'Category' => 'Transportation', 'Subcategory' => 'Navigation'],
            ['Skill_Title' => 'GPS navigation', 'Category' => 'Transportation', 'Subcategory' => 'Navigation'],
            ['Skill_Title' => 'Defensive driving', 'Category' => 'Transportation', 'Subcategory' => 'Vehicle'],
            ['Skill_Title' => 'Vehicle maintenance', 'Category' => 'Transportation', 'Subcategory' => 'Vehicle'],
            ['Skill_Title' => 'Off-road driving', 'Category' => 'Transportation', 'Subcategory' => 'Vehicle'],
            ['Skill_Title' => 'Sailing', 'Category' => 'Transportation', 'Subcategory' => 'Vehicle'],
            ['Skill_Title' => 'Piloting', 'Category' => 'Transportation', 'Subcategory' => 'Vehicle'],

            // 🌲 Survival & Outdoor Skills
            ['Skill_Title' => 'First aid', 'Category' => 'Survival', 'Subcategory' => 'Emergency'],
            ['Skill_Title' => 'Fire starting', 'Category' => 'Survival', 'Subcategory' => 'Wilderness'],
            ['Skill_Title' => 'Shelter building', 'Category' => 'Survival', 'Subcategory' => 'Wilderness'],
            ['Skill_Title' => 'Camping', 'Category' => 'Survival', 'Subcategory' => 'Outdoor'],
            ['Skill_Title' => 'Fishing', 'Category' => 'Survival', 'Subcategory' => 'Wilderness'],
            ['Skill_Title' => 'Hunting', 'Category' => 'Survival', 'Subcategory' => 'Wilderness'],
            ['Skill_Title' => 'Foraging', 'Category' => 'Survival', 'Subcategory' => 'Wilderness'],
            ['Skill_Title' => 'Knot tying', 'Category' => 'Survival', 'Subcategory' => 'Wilderness'],
            ['Skill_Title' => 'Water purification', 'Category' => 'Survival', 'Subcategory' => 'Wilderness'],
            ['Skill_Title' => 'Weather observation', 'Category' => 'Survival', 'Subcategory' => 'Wilderness'],
            ['Skill_Title' => 'Wilderness survival', 'Category' => 'Survival', 'Subcategory' => 'Wilderness'],
            ['Skill_Title' => 'Emergency preparedness', 'Category' => 'Survival', 'Subcategory' => 'Emergency'],

            // 🩺 Care & Emergency Skills
            ['Skill_Title' => 'CPR', 'Category' => 'Care & Emergency', 'Subcategory' => 'Emergency'],
            ['Skill_Title' => 'Basic life support', 'Category' => 'Care & Emergency', 'Subcategory' => 'Emergency'],
            ['Skill_Title' => 'Patient care', 'Category' => 'Care & Emergency', 'Subcategory' => 'Care'],
            ['Skill_Title' => 'Elder care', 'Category' => 'Care & Emergency', 'Subcategory' => 'Care'],
            ['Skill_Title' => 'Mental-health first aid', 'Category' => 'Care & Emergency', 'Subcategory' => 'Emergency'],
            ['Skill_Title' => 'Emergency response', 'Category' => 'Care & Emergency', 'Subcategory' => 'Emergency'],
            ['Skill_Title' => 'Disaster preparedness', 'Category' => 'Care & Emergency', 'Subcategory' => 'Emergency'],
            ['Skill_Title' => 'Rescue techniques', 'Category' => 'Care & Emergency', 'Subcategory' => 'Emergency'],

            // 🌎 Language & Cultural Skills
            ['Skill_Title' => 'Speaking languages', 'Category' => 'Language & Cultural', 'Subcategory' => 'Language'],
            ['Skill_Title' => 'Reading languages', 'Category' => 'Language & Cultural', 'Subcategory' => 'Language'],
            ['Skill_Title' => 'Writing languages', 'Category' => 'Language & Cultural', 'Subcategory' => 'Language'],
            ['Skill_Title' => 'Interpretation', 'Category' => 'Language & Cultural', 'Subcategory' => 'Language'],
            ['Skill_Title' => 'Sign language', 'Category' => 'Language & Cultural', 'Subcategory' => 'Language'],
            ['Skill_Title' => 'Pronunciation', 'Category' => 'Language & Cultural', 'Subcategory' => 'Language'],
            ['Skill_Title' => 'Grammar', 'Category' => 'Language & Cultural', 'Subcategory' => 'Language'],
            ['Skill_Title' => 'Vocabulary', 'Category' => 'Language & Cultural', 'Subcategory' => 'Language'],
            ['Skill_Title' => 'Cultural communication', 'Category' => 'Language & Cultural', 'Subcategory' => 'Culture'],
            ['Skill_Title' => 'Cross-cultural communication', 'Category' => 'Language & Cultural', 'Subcategory' => 'Culture'],

            // 🧑‍⚖️ Legal, Civic & Government Skills
            ['Skill_Title' => 'Legal research', 'Category' => 'Legal & Civic', 'Subcategory' => 'Legal'],
            ['Skill_Title' => 'Policy analysis', 'Category' => 'Legal & Civic', 'Subcategory' => 'Policy'],
            ['Skill_Title' => 'Advocacy', 'Category' => 'Legal & Civic', 'Subcategory' => 'Community'],
            ['Skill_Title' => 'Public administration', 'Category' => 'Legal & Civic', 'Subcategory' => 'Government'],
            ['Skill_Title' => 'Civic participation', 'Category' => 'Legal & Civic', 'Subcategory' => 'Community'],
            ['Skill_Title' => 'Mediation', 'Category' => 'Legal & Civic', 'Subcategory' => 'Conflict'],
            ['Skill_Title' => 'Documentation', 'Category' => 'Legal & Civic', 'Subcategory' => 'Legal'],
            ['Skill_Title' => 'Compliance', 'Category' => 'Legal & Civic', 'Subcategory' => 'Legal'],
            ['Skill_Title' => 'Contract analysis', 'Category' => 'Legal & Civic', 'Subcategory' => 'Legal'],
            ['Skill_Title' => 'Regulatory knowledge', 'Category' => 'Legal & Civic', 'Subcategory' => 'Government'],

            // 🔐 Security Skills
            ['Skill_Title' => 'Physical security', 'Category' => 'Security', 'Subcategory' => 'Security'],
            ['Skill_Title' => 'Cybersecurity', 'Category' => 'Security', 'Subcategory' => 'IT Security'],
            ['Skill_Title' => 'Network security', 'Category' => 'Security', 'Subcategory' => 'IT Security'],
            ['Skill_Title' => 'Information security', 'Category' => 'Security', 'Subcategory' => 'IT Security'],
            ['Skill_Title' => 'Risk assessment', 'Category' => 'Security', 'Subcategory' => 'IT Security'],
            ['Skill_Title' => 'Threat analysis', 'Category' => 'Security', 'Subcategory' => 'IT Security'],
            ['Skill_Title' => 'Incident response', 'Category' => 'Security', 'Subcategory' => 'IT Security'],
            ['Skill_Title' => 'Security auditing', 'Category' => 'Security', 'Subcategory' => 'IT Security'],
            ['Skill_Title' => 'Access control', 'Category' => 'Security', 'Subcategory' => 'Security'],
            ['Skill_Title' => 'Surveillance awareness', 'Category' => 'Security', 'Subcategory' => 'Security'],

            // 💰 Financial Skills
            ['Skill_Title' => 'Budgeting', 'Category' => 'Financial', 'Subcategory' => 'Personal Finance'],
            ['Skill_Title' => 'Saving', 'Category' => 'Financial', 'Subcategory' => 'Personal Finance'],
            ['Skill_Title' => 'Investing', 'Category' => 'Financial', 'Subcategory' => 'Investment'],
            ['Skill_Title' => 'Tax preparation', 'Category' => 'Financial', 'Subcategory' => 'Accounting'],
            ['Skill_Title' => 'Financial planning', 'Category' => 'Financial', 'Subcategory' => 'Personal Finance'],
            ['Skill_Title' => 'Financial analysis', 'Category' => 'Financial', 'Subcategory' => 'Business'],
            ['Skill_Title' => 'Cost estimation', 'Category' => 'Financial', 'Subcategory' => 'Business'],
            ['Skill_Title' => 'Negotiating prices', 'Category' => 'Financial', 'Subcategory' => 'Sales'],
            ['Skill_Title' => 'Debt management', 'Category' => 'Financial', 'Subcategory' => 'Personal Finance'],
            ['Skill_Title' => 'Business finance', 'Category' => 'Financial', 'Subcategory' => 'Business'],

            // 🛠️ Specialized / Professional Trades
            ['Skill_Title' => 'Electrician', 'Category' => 'Specialized Trades', 'Subcategory' => 'Construction'],
            ['Skill_Title' => 'Plumber', 'Category' => 'Specialized Trades', 'Subcategory' => 'Construction'],
            ['Skill_Title' => 'Welder', 'Category' => 'Specialized Trades', 'Subcategory' => 'Manufacturing'],
            ['Skill_Title' => 'Mechanic', 'Category' => 'Specialized Trades', 'Subcategory' => 'Vehicle'],
            ['Skill_Title' => 'Machinist', 'Category' => 'Specialized Trades', 'Subcategory' => 'Manufacturing'],
            ['Skill_Title' => 'Carpenter', 'Category' => 'Specialized Trades', 'Subcategory' => 'Construction'],
            ['Skill_Title' => 'Mason', 'Category' => 'Specialized Trades', 'Subcategory' => 'Construction'],
            ['Skill_Title' => 'Barber', 'Category' => 'Specialized Trades', 'Subcategory' => 'Personal'],
            ['Skill_Title' => 'Hairdresser', 'Category' => 'Specialized Trades', 'Subcategory' => 'Personal'],
            ['Skill_Title' => 'Chef', 'Category' => 'Specialized Trades', 'Subcategory' => 'Food'],
            ['Skill_Title' => 'Baker', 'Category' => 'Specialized Trades', 'Subcategory' => 'Food'],
            ['Skill_Title' => 'Tailor', 'Category' => 'Specialized Trades', 'Subcategory' => 'Crafts'],
            ['Skill_Title' => 'Photographer', 'Category' => 'Specialized Trades', 'Subcategory' => 'Media'],
            ['Skill_Title' => 'Videographer', 'Category' => 'Specialized Trades', 'Subcategory' => 'Media'],
            ['Skill_Title' => 'Surveyor', 'Category' => 'Specialized Trades', 'Subcategory' => 'Construction'],
            ['Skill_Title' => 'Architect', 'Category' => 'Specialized Trades', 'Subcategory' => 'Design'],
            ['Skill_Title' => 'Engineer', 'Category' => 'Specialized Trades', 'Subcategory' => 'Engineering'],
            ['Skill_Title' => 'Nurse', 'Category' => 'Specialized Trades', 'Subcategory' => 'Healthcare'],
            ['Skill_Title' => 'Teacher', 'Category' => 'Specialized Trades', 'Subcategory' => 'Education'],
            ['Skill_Title' => 'Lawyer', 'Category' => 'Specialized Trades', 'Subcategory' => 'Legal'],
            ['Skill_Title' => 'Accountant', 'Category' => 'Specialized Trades', 'Subcategory' => 'Finance'],
            ['Skill_Title' => 'Programmer', 'Category' => 'Specialized Trades', 'Subcategory' => 'Technology'],
            ['Skill_Title' => 'Designer', 'Category' => 'Specialized Trades', 'Subcategory' => 'Design'],
            ['Skill_Title' => 'Technician', 'Category' => 'Specialized Trades', 'Subcategory' => 'Technical'],

            // 🎮 Entertainment & Gaming Skills
            ['Skill_Title' => 'Video gaming', 'Category' => 'Entertainment & Gaming', 'Subcategory' => 'Gaming'],
            ['Skill_Title' => 'Esports', 'Category' => 'Entertainment & Gaming', 'Subcategory' => 'Gaming'],
            ['Skill_Title' => 'Game strategy', 'Category' => 'Entertainment & Gaming', 'Subcategory' => 'Gaming'],
            ['Skill_Title' => 'Game design', 'Category' => 'Entertainment & Gaming', 'Subcategory' => 'Development'],
            ['Skill_Title' => 'Level design', 'Category' => 'Entertainment & Gaming', 'Subcategory' => 'Development'],
            ['Skill_Title' => 'Game development', 'Category' => 'Entertainment & Gaming', 'Subcategory' => 'Development'],
            ['Skill_Title' => 'Streaming', 'Category' => 'Entertainment & Gaming', 'Subcategory' => 'Media'],
            ['Skill_Title' => 'Commentary', 'Category' => 'Entertainment & Gaming', 'Subcategory' => 'Media'],
            ['Skill_Title' => 'Voice acting', 'Category' => 'Entertainment & Gaming', 'Subcategory' => 'Performance'],
            ['Skill_Title' => 'Cosplay', 'Category' => 'Entertainment & Gaming', 'Subcategory' => 'Performance'],
            ['Skill_Title' => 'DJing', 'Category' => 'Entertainment & Gaming', 'Subcategory' => 'Music'],
            ['Skill_Title' => 'Music production', 'Category' => 'Entertainment & Gaming', 'Subcategory' => 'Music'],
            ['Skill_Title' => 'Mixing', 'Category' => 'Entertainment & Gaming', 'Subcategory' => 'Audio'],
            ['Skill_Title' => 'Sound design', 'Category' => 'Entertainment & Gaming', 'Subcategory' => 'Audio'],

            // 🧩 Very Specific / Miscellaneous Skills
            ['Skill_Title' => 'Lockpicking', 'Category' => 'Miscellaneous', 'Subcategory' => 'Practical'],
            ['Skill_Title' => 'Juggling', 'Category' => 'Miscellaneous', 'Subcategory' => 'Performance'],
            ['Skill_Title' => 'Card tricks', 'Category' => 'Miscellaneous', 'Subcategory' => 'Performance'],
            ['Skill_Title' => 'Magic', 'Category' => 'Miscellaneous', 'Subcategory' => 'Performance'],
            ['Skill_Title' => 'Origami', 'Category' => 'Miscellaneous', 'Subcategory' => 'Crafts'],
            ['Skill_Title' => 'Chess', 'Category' => 'Miscellaneous', 'Subcategory' => 'Games'],
            ['Skill_Title' => 'Speedcubing', 'Category' => 'Miscellaneous', 'Subcategory' => 'Games'],
            ['Skill_Title' => 'Whistling', 'Category' => 'Miscellaneous', 'Subcategory' => 'Practical'],
            ['Skill_Title' => 'Beatboxing', 'Category' => 'Miscellaneous', 'Subcategory' => 'Music'],
            ['Skill_Title' => 'Bartending', 'Category' => 'Miscellaneous', 'Subcategory' => 'Food'],
            ['Skill_Title' => 'Coffee making', 'Category' => 'Miscellaneous', 'Subcategory' => 'Food'],
            ['Skill_Title' => 'Latte art', 'Category' => 'Miscellaneous', 'Subcategory' => 'Food'],
            ['Skill_Title' => 'Archery', 'Category' => 'Miscellaneous', 'Subcategory' => 'Sports'],
            ['Skill_Title' => 'Coin collecting', 'Category' => 'Miscellaneous', 'Subcategory' => 'Collecting'],
            ['Skill_Title' => 'Bird watching', 'Category' => 'Miscellaneous', 'Subcategory' => 'Hobby'],
            ['Skill_Title' => 'Geocaching', 'Category' => 'Miscellaneous', 'Subcategory' => 'Hobby'],
            ['Skill_Title' => 'Genealogy', 'Category' => 'Miscellaneous', 'Subcategory' => 'Research'],
            ['Skill_Title' => 'Metal detecting', 'Category' => 'Miscellaneous', 'Subcategory' => 'Hobby'],
            ['Skill_Title' => 'Memorizing numbers', 'Category' => 'Miscellaneous', 'Subcategory' => 'Mental'],
            ['Skill_Title' => 'Speed reading', 'Category' => 'Miscellaneous', 'Subcategory' => 'Learning'],
            ['Skill_Title' => 'Typing', 'Category' => 'Miscellaneous', 'Subcategory' => 'Computer'],
            ['Skill_Title' => 'Shorthand', 'Category' => 'Miscellaneous', 'Subcategory' => 'Writing'],
            ['Skill_Title' => 'DJ mixing', 'Category' => 'Miscellaneous', 'Subcategory' => 'Audio'],
        ];

        DB::table('skills')->insertOrIgnore($skills);
    }
}
